### ISSUE TITLE
Any hope for GLES support?

### ISSUE THREAD

**Issue by vanfanel** [sezero/quakespasm#1]
Hi there. @ericwa 

Is there any hope that Quakespasm gets GLES support?
It would be specially interesting for X-less, running Quakespasm without an X server.
Nowadays, SDL2 runs perfectly on KMSDRM thanks to it's KMSDRM backend, no X is needed. But for that, only GLES is supported in some platforms like the Raspberry Pi (using the standard KMS/DRM graphics stack, NOT the old and deprecated Broadcom stuff).

**Comment by sezero** [comment]
Nope, I guess

**Comment by vanfanel** [comment]
Forward into 2022, the pi supports full OpenGL without stinky X11, vía mesa built with GLVND support.
So this is not an issue anymore! Thanks @sezero
