### ISSUE TITLE
issues with map starslave

### ISSUE THREAD

**Issue by j4reporting** [sezero/quakespasm#108]
reported on [slipseer](https://www.slipseer.com/index.php?threads/starslave.419/post-3624 ). 
map: [starslave v1.3 ](https://www.slipseer.com/index.php?resources/starslave.298/) 

In the first room in the pyramid there are already 3 ammo boxes visible  that don't exist.  You can't see any objects (quad) in the hallway  leading to the next room.   The scrags are also "not there".
Compare with vkquake screenshots.

![spasm0000](https://github.com/user-attachments/assets/c9ffcf58-ccd0-4006-a4fb-acb963ef97c5)
![spasm0001](https://github.com/user-attachments/assets/232b4aa7-0f79-4c0a-8ce7-47c90e1e52e7)
![spasm0002](https://github.com/user-attachments/assets/4db6d9c3-ee13-4181-b9a1-a85570bd2a92)

vkquake:
![vkquake0000](https://github.com/user-attachments/assets/548ce405-f8ee-48f4-a975-ca6e53d04bfb)
![vkquake0001](https://github.com/user-attachments/assets/fc6dffe7-b061-4527-9289-6a5b22dbae79)

**Comment by sezero** [comment]
It seems to require protocol 999
