### ISSUE TITLE
Global Functionality to 'nomonsters' cvar (Ironwail revision)

### ISSUE THREAD

**Issue by MrTenThirteen** [sezero/quakespasm#109]
Hello there,

Over the last couple years I've been investigating and researching as much as I could to find out about Quake's 'nomonsters' cvar, which is a listed console command in the release game but does not function. Certain mods, such as Arcane Dimensions or Copper, restores it, but what I've been looking for is global functionality. I understand that very few people are even interested in it outside of testing / debugging purposes, but I genuinely quite enjoy playing games such as Quake, Unreal, Daikatana, etc. with no combat at all, and just exploring.

A fork of your source port - Ironwail - restores global functionality through a revision, 91d630d, which is wonderful, and just what I've been looking for. Unfortunately, I can't run Ironwail on my computer. I can run Quakespasm, though, and when I opened an issue on the Ironwail github page to ask if there's a way for me to implement the revision into Quakespasm, it was suggested that I open an issue here.

Is it possible to implement this revision into Quakespasm proper?

For everyone else interested, this would be a useful feature for testing / debugging purposes, and for strange people like myself, we could explore any maps from any Quake release without combat. Yes, it would break certain things in the game, but I believe the Ironwail revision code addresses some of that, and personally, I play games set up like this at my own risk anyways.

Thank you

**Comment by sezero** [comment]
Will look, but no ETA or promises at all.

In the meantime, you can use `notarget` to avoid battle in most cases.

**Comment by Diordany** [comment]
I decided to try this out. I resolved the merge conflicts in [this commit](https://github.com/Diordany/quakespasm/commit/d6575f5ba34ebbc1d7e2fb81ff58fb5d3c8a7fef) and tested this with both SDL1.2 and SDL2. Seems to work fine so far. The checks were also successful.

**Comment by sezero** [comment]
> I decided to try this out. I resolved the merge conflicts in [this commit](https://github.com/Diordany/quakespasm/commit/d6575f5ba34ebbc1d7e2fb81ff58fb5d3c8a7fef) and tested this with both SDL1.2 and SDL2. Seems to work fine so far. The checks were also successful.

Create a pull request please.

@andrei-drexler: Have you encountered any issues with that nomonsters patch so far?

**Comment by Diordany** [comment]
> Create a pull request please.

Opened PR in #110

**Comment by MrTenThirteen** [comment]
@sezero I understand about no ETA or promises. This is a niche request. I'm grateful that you all are looking into it so promptly and thoroughly. Thank you very much.

**Comment by sezero** [comment]
OK, the patch is in. Let's see if it leads to any unlikely issues.

**Comment by andrei-drexler** [comment]
> @andrei-drexler: Have you encountered any issues with that nomonsters patch so far?

I haven't had any reports, but it can probably cause issues with events not triggering because of the missing monsters, hence the warning and the disabled saves. I don't think there's a reliable way to avoid that, though.
