### ISSUE TITLE
[Bug] ENT files not loaded in SoA/DoE

### ISSUE THREAD

**Issue by NightFright2k19** [sezero/quakespasm#11]
In spite of using correct checksums for .ent files in SoA and DoE (e.g. hip1m1@061e.ent for Kex version of HIP1M1 or r1m1@490b.ent for Kex version of R1M1), definitions are not loaded. It also does not work after removing checksum part completely (e.g. h1m1.ent).

Can be easily checked by altering map title in .ent file and loading it with the map afterwards. ID1 seems to work as intended. [Same issue in Quakespasm-Spiked x64 v2021-10-06.](https://github.com/Shpoike/Quakespasm/issues/84)

Tested with: Quakespasm 0.94.1 (x64)

[Test files for HIP1M1 and R1M1](https://mega.nz/file/4VAiULwT#a91PJ6rSRnxkDg2ZYOnbSBmULBqMW6ElGr6osqzoqI4)

**Comment by sezero** [comment]
Can't reproduce in latest git. Put the relevant ent files under hipnotic/maps/ and rogue/maps/
and it seems to work:
```
]developer 1
]map hip1m1
SpawnServer: hip1m1
Clearing memory
Programs occupy 634K.
trying to open external vis file
maps/hip1m1.vis not found, trying hipnotic.vis
external vis not found
Loaded external entity file maps/hip1m1@b99a.ent
45 entities inhibited
Server spawned.
CL_EstablishConnection: connected to local
Client LOCAL connected
```
```
]developer 1
]map r1m1
SpawnServer: r1m1
Clearing memory
Programs occupy 704K.
trying to open external vis file
maps/r1m1.vis not found, trying rogue.vis
external vis not found
Loaded external entity file maps/r1m1@5379.ent
112 entities inhibited
Server spawned.
CL_EstablishConnection: connected to local
Client LOCAL connected
```

**Comment by sezero** [comment]
I imagine that you are putting hipnotic and rogue ents under id1/maps/ instead of hiptonic/maps/ and rouge/maps/
If that is the case, it is the reason for the failure.

**Comment by sezero** [comment]
quakespasm.pak has the same priority as id1/*, hence the failure.

**Comment by NightFright2k19** [comment]
I see. Well, with the checksum feature, it would at least theoretically be possible to also support hipnotic and rogue subdirs, provided it's considered to be useful. 

General assumption from my side was: ID1 content is also loaded with SoA and DoE, so if quakespasm.pak is pulled in by ID1, its content should also be available in hipnotic or rogue subdirs.
