### ISSUE TITLE
Some issues with colors on Big Endian system

### ISSUE THREAD

**Issue by Link4Electronics** [sezero/quakespasm#114]
Running Debian sid PPC64 on a powermac g5, using Radeon R5 230 terascale 2 gpu and mesa r600g drivers, quakespasm runs but the colors of some textures doesn't look right.
![20241114_182420](https://github.com/user-attachments/assets/6a323301-33a1-40f3-b012-84680b6873cf)
![20241114_182440](https://github.com/user-attachments/assets/661147d7-11bf-4860-aa08-106600cf1eb9)
![20241114_183919](https://github.com/user-attachments/assets/b17a5588-50f7-461b-8179-5d224fad01ee)
it looks like that it's more bright than it should, and the brightness is already at the lowest 1.00, enemies don't drop blood on the floor when they got hit or die either.
For comparison, Darkplaces running on the same machine
![20241114_182455](https://github.com/user-attachments/assets/e58ca82f-368e-48d9-8581-5d76d0c6df6a)
![20241114_182514](https://github.com/user-attachments/assets/d476fe36-9771-4049-ba5c-968ac82c743a)
![20241114_184028](https://github.com/user-attachments/assets/fc282cb7-e223-41e5-9141-93c64073b4e2)

Best regards,
Link.

**Comment by sezero** [comment]
Unfortunately I don't have a big endian system around to test, and hunting through the code just by eyeballing would be extremely hard.

Assuming you have debugging / programming skills: do you have a patch?

CC: @ericwa, @kduske (maybe also @Shpoike and @andrei-drexler)

**Comment by andrei-drexler** [comment]
It looks like maybe there's some underflow/wraparound in the dlight code. I'm wondering if it's specific to the EXT_packed_pixels codepath.

@Link4Electronics can you try running the executable with `-nopackedpixels`?

**Comment by Link4Electronics** [comment]
Yeap, running with -nopackedpixels made all the difference
![20241114_190732](https://github.com/user-attachments/assets/fad28c96-fb48-463d-a9be-d7c8ef727bdd)
![20241114_190734](https://github.com/user-attachments/assets/e6f3a85d-fe10-46b7-a92c-0cbf9d431f5e)
Looks much better.

**Comment by sezero** [comment]
> It looks like maybe there's some underflow/wraparound in the dlight code. I'm wondering if it's specific to the EXT_packed_pixels codepath.
> 
> @Link4Electronics can you try running the executable with `-nopackedpixels`?

> Yeap, running with -nopackedpixels made all the difference

Interesting.. @andrei-drexler: do you have a patch ?

**Comment by andrei-drexler** [comment]
Not at the moment, but I'll try to take a look at the code this weekend and see if I spot anything.

**Comment by sezero** [comment]
> Not at the moment, but I'll try to take a look at the code this weekend and see if I spot anything.

Thanks.  What's confusing to me is that why any issues doesn't show up on x86 or little endian...

**Comment by andrei-drexler** [comment]
You're right, it doesn't make much sense for the issue to actually be an underflow that somehow doesn't manifest on x86/LE, it's just that the first image looks like that - the light caused by the explosion falls off and then wraps around. It's more likely IMO that the GL_UNSIGNED_INT_10_10_10_2 data is getting swizzled incorrectly. I took a quick look at the code and haven't spotted anything wrong, though, so this could also be a driver bug... Maybe gl_packed_pixels should just be disabled on big endian systems to avoid this issue altogether?

```diff
--- a/Quake/gl_vidsdl.c
+++ b/Quake/gl_vidsdl.c
@@ -1276,6 +1276,8 @@ static void GL_CheckExtensions (void)
 	//
 	if (COM_CheckParm("-nopackedpixels"))
 		Con_Warning ("EXT_packed_pixels disabled at command line\n");
+	else if (host_bigendian)
+		Con_Warning ("EXT_packed_pixels disabled on big endian systems");
 	else if (gl_glsl_alias_able)
 	{
 		gl_packed_pixels = true;
```

**Comment by Link4Electronics** [comment]
Now that you mention about the driver, mesa 24.1.6, quakespasm is running on OpenGL 3.2 Compatibility Profile, not Core Profile, don't know if makes any difference, but shouldn't be running on core profile?

**Comment by sezero** [comment]
I went ahead and applied the proposed patch as https://github.com/sezero/quakespasm/commit/958fb63b201b73bcf3a0944b23fad91f4e536328 with a FIXME note.

Thanks.
