### ISSUE TITLE
certain .ent files not loading

### ISSUE THREAD

**Issue by timbergeron** [sezero/quakespasm#13]
outputted .ent file for e1m1, e1m2, e1m4, e2m2, e2m3, e2m7 (using ericw-tools-v0.18.1-90-g03ed069-win64) does not load while 95%+ of all other .ents do

tested in 0.94.3

**Comment by sezero** [comment]
You aren't giving me anything to test with - if you give me one example ent that doesn't load then maybe I can help, otherwise I can't.

**Comment by timbergeron** [comment]
[ents.zip](https://github.com/sezero/quakespasm/files/7707603/ents.zip)

simple test changing the map name

e1m2 does not work, e1m3 does work

**Comment by sezero** [comment]
It seems like quakespasm.pak is getting in the way: quakespasm.pak has a crc-versioned version of e1m2.ent as `e1m2@0caa.ent` and it is loaded. If I remove or rename quakespasm.pak, your e1m2.ent is loaded.

**Comment by timbergeron** [comment]
cool thanks, why do those specific maps have .ents in the qs pak? just curious

**Comment by sezero** [comment]
They have some z-fighting fixes in them.

**Comment by timbergeron** [comment]
cool. thanks for such prompt responses :)
