### ISSUE TITLE
Some Quality of Life features that aren't too radical

### ISSUE THREAD

**Issue by tunbridgep** [sezero/quakespasm#15]
Hey, I love this port! It runs way better than Darkplaces on my Linux box, doesn't bloat my game with extra "effects" (I especially hate the way model interp works in darkplaces because the nailgun fires weirdly and you can see a nail travel between both barrels), it's nearly perfect for me.

I do however feel it is a tad rough around the edges in some ways.

I have a few suggestions for some more modern QoL features (which should all be optional) to make it slightly more playable in lieu of what is considered to be core features of modern games. Please understand I grew up largely with modern games and this has been a throwback for me, and seeing some core features not available is really difficult to get used to.

The main pain point is saving, which has been automated in some very nice ways in more modern games, in ways I feel aren't detrimental to the experience and are actually quite positive.

I understand that one of the goals of this port is authenticity, without adding too many bloated features. However, I feel that taking the good while fixing the bad is a good way to improve something without fundamentally changing it.

Anyway, some saving suggestions:

1. Please add a setting (possibly on by default as people may get caught out) which will autosave in a new slot at the start of every map (except the title map). Autosaves are common in modern games and it would be easy for someone playing Quake now to die and lose multiple hours of progress, not realising they haven't saved in a while. I died a few times on a level and upon pressing fire it restarted, and seemed to have my same inventory, so I think it's already autosaving to some extent, it would just be nice to do it explicitly so we can quit the game and not lose our progress.
2. Pressing the fire button when dead should load the last save available rather than throwing you back to the start of the level
3. In the same vein, please add a quicksave and quickload hotkey to the controls, bound to F5 and F9 by default. I like that I can quicksave but it would be nice to be able to change the button in-game

Some other suggestions:
1. Please add keybinds for every weapon key to the controls menu, so we can bind them specially if we want.
3. Many of us have screens that are much higher resolution than the game was designed for, which makes the menu really small, even when scaled. As a result, having to go into the Single Player menu just to load or save is really inconvenient, especially when there's enough space on the screen now to fit every menu item at once, especially if you get rid of the useless Help/Ordering button. A "simplified menu" option could help with this, which makes the menu more like Doom (all options available at once, no submenus). I get that it's not authentic, though, and is probably the worst suggestion on this list.
4. (This is the most controversial and will likely get the most hate in the comments) More modern games (many in the same vein as Quake such as Half Life) have a "Last weapon used" button. I feel it could be useful here as quick weapon swaps are a core part of Quake. I get that it's technically a gameplay change and could have multiplayer implications (as well as others), so maybe it should be singleplayer only.
5. The ability to turn off "Auto select pickup weapons" with 3 settings - on, which is as of now, off, which completely disables it, and partial which only switches to weapons we don't have yet.

Also, I know they are pretty terrible, but does this port have support for any of the official expansions at all?

Lastly, completely unrelated, does anyone know a good source port for Hexen 2? I intend to play that after this. I have found a few in the past but they all seemed to be very feature bloated or broken.

**Comment by NightFright2k19** [comment]
Official Q1 expansions "pretty terrible"?! Are you sober? SoA is at least as good as the original game, if not better! DoE can be debated, but it has its moments. And ofc Quakespasm supports both of them, just like any other port out there. Oh, and DOPA + DOTM from the Quake Re-Release work, too.

As for Hexen 2, the port to go would probably be [Hammer of Thyrion](http://uhexen2.sourceforge.net/).

**Comment by sezero** [comment]
Most, if not all, of the requests here are progs-controlled unless I'm misreading things. Closing.
