### ISSUE TITLE
Add ability to load QuakeEX.kpf from gamedir

### ISSUE THREAD

**Issue by mmillar-bolis** [sezero/quakespasm#17]
Thank you for all of the great work in supporting localization!

Currently, QuakeSpasm supports loading `QuakeEX.kpf` from the `basedir`, or on Linux from the `userdir` as well. It would be nice if support was added to read from the `gamedir` for the players who use old release Quake and only want to load the `.kpf` when playing `mg1` or a mod that specifically needs it.

**Comment by sezero** [comment]
I don't think that's what quakeex does, so no.
