### ISSUE TITLE
no audio with Intel Display Audio devices

### ISSUE THREAD

**Issue by j4reporting** [sezero/quakespasm#23]
Audio is not initialized on WIndows if 'Intel display audio'  is the only available audio device AND a modeset is issued.
This is a known issue with Intel Drivers (see [Intel document ](https://www.intel.com/content/www/us/en/support/articles/000035049/intel-nuc/intel-nuc-kits.html) ).  

```
Sound Initlalisation
Coundn't opem SDL audio:  WASAPI can't find requested audio endpoint: Element not found.
```

I could fix this by simply retrying again 2 seconds later. 

Unfortunately audio device is also lost later in the game when switching to another video resolution or  switching from vid_fullscreen 0 <-> 1.
What is needed is some kind of   snd_restart  command  and ideally a check if the audio device is available  and if not,  an automatic restart of the audio device.

the same issue can be observed with vkQuake, Ironwail and probably with other forks.

Why had  that worked for me all this years?  I had a headphone connected to the system ( realtek HD audio) and Quakespasm would find the headphone, initialize audio  and when Intel Display Audio re-apperared,  SDL/ WASAPI  would switch back to the default audio device!

**Comment by sezero** [comment]
This issue might be handled by SDL: Have you reported it to SDL?

@ericwa, @andrei-drexler, @Novum: Any of you guys ran into this? Suggestions?

**Comment by sezero** [comment]
issue reported to SDL - https://github.com/libsdl-org/SDL/issues/5571
