### ISSUE TITLE
call modeset only when needed

### ISSUE THREAD

**Issue by j4reporting** [sezero/quakespasm#24]
it seems that quakespasm and ironwail  are issuing a modeset even when it's not needed.
A modeset occurs if game resolution and framerate matches the desktop settings.  vkQuake seem to issue a modeset only if  resolution or framerate differ from desktop settings.

with vid_fullscreen 0     a modeset is called as well if game resolution matched the desktop resolution. 
With 'Intel Display Audio' devices this leads to uninitialized/lost  audio.

**Comment by sezero** [comment]
dup of #23
