### ISSUE TITLE
Stack corruption when printing edicts

### ISSUE THREAD

**Issue by alexey-lysiuk** [sezero/quakespasm#25]
There is a potential write outside of stack buffer inside `PR_ValueString()` function.
To reproduce, load [Oozing Blasphemy](https://www.quaddicted.com/filebase/ad_blasphemy.zip) with [Arcane Dimensions 1.81](https://www.quaddicted.com/filebase/ad_v1_80p1final.zip), and do `edicts` in console.

It may crash at the following line
https://github.com/sezero/quakespasm/blob/33085c5449ada97524ef0a5798519f7e4409c207/Quake/pr_edict.c#L321 because of attempt to write more bytes than were "allocated" here
https://github.com/sezero/quakespasm/blob/33085c5449ada97524ef0a5798519f7e4409c207/Quake/pr_edict.c#L312

Should it allocate a temporary buffer on the heap if stack one is too small?
Or, is it better to just use `q_snprintf()` to output only value's part?

**Comment by sezero** [comment]
The `wad` entry is ridiculously long -  q_snprintf is the way to go: will apply [this patch](https://github.com/sezero/quakespasm/files/8547375/patch.txt) shortly

**Comment by sezero** [comment]
Should be fixed by commit 1c970af
