### ISSUE TITLE
Provide a detailed documentation on how to compile and run the engine

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [sezero/quakespasm#26]
Hi,

I played Quake1 with Quakespasm several years ago on Windows and it was pretty easy to install and run the game.
I have quake1 .pak files and now I want to install the latest quakespasm and play the game on Linux natively without Wine. 
There is a Linux package of `quakespasm` but, honestly, I have no idea how to compile or even run the engine with the game.
I was not able to find any required information on this in the archive. `Quakespasm.txt` says `See the Downloads section to get the sourcecode, then below for platform specific instructions.` but there is no information on how to compile and run it under the Downloads section. There is also not much information on the internet on how to do it.

vkQuake does a better job on this - there is a clear instruction in their repo. Nevertheless, I am not sure how much it is compatible with mods like Quakespasm .

**Comment by sezero** [comment]
Build instructions look clear to me:
https://github.com/sezero/quakespasm/blob/master/Quakespasm.txt#L223
