### ISSUE TITLE
bug: vid_restart with external textures (windowed to/from fullscreen)

### ISSUE THREAD

**Issue by timbergeron** [sezero/quakespasm#28]
version: latest release

After a toggle between window/fullscreen which uses vid_restart external textures with _glow or _luma overbright textures (see below images)

tested using QRP textures

![spasm0001](https://user-images.githubusercontent.com/68674590/179282170-c431957f-8118-449d-a41c-6d71f4fee0e5.png)
![spasm0000](https://user-images.githubusercontent.com/68674590/179282174-4d1b9678-160e-4d7b-a2c1-060433500d8a.png)

**Comment by sezero** [comment]
@ericwa, @andrei-drexler: any insight?

**Comment by andrei-drexler** [comment]
This should do it:
```diff
diff --git a/Quake/gl_model.c b/Quake/gl_model.c
index fe8ac6a..001f38c 100644
--- a/Quake/gl_model.c
+++ b/Quake/gl_model.c
@@ -612,7 +612,7 @@ void Mod_LoadTextures (lump_t *l)
 
 					if (data)
 						tx->fullbright = TexMgr_LoadImage (loadmodel, filename2, fwidth, fheight,
-							SRC_RGBA, data, filename, 0, TEXPREF_MIPMAP | extraflags );
+							SRC_RGBA, data, filename2, 0, TEXPREF_MIPMAP | extraflags );
 				}
 				else //use the texture from the bsp file
 				{
```

**Comment by sezero** [comment]
Oh boy, it's always been there I guess. Patch is in, thanks!
