### ISSUE TITLE
fix/bug: ext texture loading for unnamed textures

### ISSUE THREAD

**Issue by timbergeron** [sezero/quakespasm#29]
A few map developers forgot to name textures in their maps and therefore they do not currently load.

The most popular map where this happens is aerowalk, which has 3 unnamed textures. 

unnamed16
unnamed17
unnamed10

Other popular maps I've discovered with unnamed textures: cmt4, ctf5

FTE fix in Mod_LoadTextures (gl_model.c)

if (!tx->name[0])
{
q_snprintf(tx->name, sizeof(tx->name), "unnamed%d", i);
Con_DPrintf("Warning: unnamed texture in %s, renaming to %s\n", loadmodel->name, tx->name);
}

**Comment by sezero** [comment]
That assumes that empty-named textures will have those `unnamed%d` counterparts which sounds silly. Does this truly work? @andrei-drexler?

**Comment by timbergeron** [comment]
imagelist without code:

![1](https://user-images.githubusercontent.com/68674590/179571011-0f91e518-bc1c-47a0-949f-5d1cc0c09e29.JPG)

imagelist with code:

![2](https://user-images.githubusercontent.com/68674590/179571033-90dfb052-d987-4051-9265-282b5ddff1ce.JPG)

quark textures:

![Capture](https://user-images.githubusercontent.com/68674590/179571066-d631a1e7-f71c-41f4-a88d-2b9a7d0af9cb.JPG)

**Comment by sezero** [comment]
I don't want to encourage mapper laziness or silliness.

Has any other engine such as ironwail or vkquake adopt this thing?
I do hope that they haven't.

**Comment by andrei-drexler** [comment]
Normally I'd agree that we shouldn't encourage carelessness, but if there are high-profile maps out there with this issue, with replacement textures already relying on this convention, I think that ship has sailed. The best solution IMO is to add the fix, but also change the Con_DPrintf to a Con_Warning to make sure that this doesn't go unnoticed in any new maps.

**Comment by sezero** [comment]
We need to know which train is it we missed then, at the least. I still very much dislike the idea and _not_ want to apply such a patch, though.

**Comment by sezero** [comment]
Well, looking at it more, this is _not_ a bug, not ours at all. Closing as WONTFIX.
