### ISSUE TITLE
Cannot bind CAPS LOCK

### ISSUE THREAD

**Issue by daftmugi** [sezero/quakespasm#30]
The scenario is that I'm using QuakeSpasm on Linux and have XKBOPTIONS="ctrl:nocaps" with the intention of using CAPS LOCK as CTRL. Most apps see the CAPS LOCK as a CTRL key, but QuakeSpasm does not. Other games have this issue as well -- seeing CAPS LOCK as CAPS LOCK instead of CTRL -- but those games allow binding CAPS LOCK.

Support for binding CAPS LOCK was added to vkQuake.
Please see https://github.com/Novum/vkQuake/commit/8bfb38e34e8890005b83bbb4aa841315fd05bddf

**Comment by sezero** [comment]
Closing as WONTFIX (see notes in https://github.com/sezero/quakespasm/pull/31)
