### ISSUE TITLE
Lightmapped liquids support

### ISSUE THREAD

**Issue by fabiolimamp** [sezero/quakespasm#33]
All major QS forks seem to be getting lit water support, enabled by compiling a map using ericw tools with the -splitturb option enabled in qbsp.

The whole Quake community feel this is a groundbreaking feature, as it increases immersion by a lot when there are liquids in the scene.

How difficult would it be to backport it to QS?

**Comment by sezero** [comment]
> How difficult would it be to backport it to QS?

Can be a lot..

Unless someone contributes a very well tested patch, I won't attempt it.

**Comment by ericwa** [comment]
Spike wrote a patch against QS 0.94.2:

https://github.com/Shpoike/Quakespasm/commit/88384bc3bf4541a9ff222311ceba9245906efdf0

If anyone feels like testing + updating this would probably be a good place to start.

**Comment by sezero** [comment]
> Spike wrote a patch against QS 0.94.2:
> 
> [Shpoike/Quakespasm@88384bc](https://github.com/Shpoike/Quakespasm/commit/88384bc3bf4541a9ff222311ceba9245906efdf0)
> 
> If anyone feels like testing + updating this would probably be a good place to start.

If you are confident about the patch, feel free to apply it to git at sf.net
