### ISSUE TITLE
Glistening effect on distant water

### ISSUE THREAD

**Issue by Flecked42** [sezero/quakespasm#38]
https://user-images.githubusercontent.com/90434262/189554968-4ea798e3-b54b-4e45-a08f-6fe6a0345987.mp4

Happens with both r_oldwater 0 and 1

For reference this doesn't happen in Ironwail or vkQuake.

**Comment by sezero** [comment]
I assume this happens with version 0.95.0, but not with 0.94.7?

@ericwa, @andrei-drexler: ideas?

**Comment by Flecked42** [comment]
It happens with both 0.95.0 and 0.94.7.

**Comment by ericwa** [comment]
When `r_oldwater` is 0, I would guess this is aliasing due to not having mipmaps on the warp image?

Could try https://www.khronos.org/opengl/wiki/Common_Mistakes#Legacy_Generation

**Comment by j0zzz** [comment]
Yeah, your tip fixed it Eric, thx a lot ❤

**Comment by sezero** [comment]
Can someone send a patch for QS git?

**Comment by Flecked42** [comment]
JoeQuake was having the same issue, which is how i stubbed upon the same issue the QS.

Looks this https://github.com/j0zzz/JoeQuake/commit/0527dd9dac8b1f4904be2e37771a21849083edd8 is the commit that fixed it in JoeQuake.

**Comment by j0zzz** [comment]
I tried adding it to QS but enabling TEXPREF_MIPMAP on the warp image makes it crash, so I would let someone else with much wider knowledge do it.

**Comment by Novum** [comment]
You need to actually generate mipmaps after rendering the warp image to fix this

**Comment by sezero** [comment]
Fixed by PR #44. Closing the ticket.
