### ISSUE TITLE
Dimension of the Machine Horde mode: broken strings

### ISSUE THREAD

**Issue by mooreye** [sezero/quakespasm#46]
When I start the game with

`quakespasm -game mg1 +map horde1`

I get a countdown 3, 2, 1, and then `$qc_horde_fight`, at least this string seems to be missing/broken.

**Comment by sezero** [comment]
You should copy `QuakeEX.kpf` from `rerelease` to your installation.

**Comment by mooreye** [comment]
I did but `localization` dir inside it doesn't seem to contain string of that name, my md5sum of this file is `ff41b8af6a0b6a283ec329429f6facdf`, is there something else I miss?

**Comment by sezero** [comment]
The md5 from what I have is `1345cbcf78b903707250c9a9638032a4` (from rerelease-update3.)

@andrei-drexler, @Novum: Any ideas?

**Comment by sezero** [comment]
>  md5sum of this file is `ff41b8af6a0b6a283ec329429f6facdf`, is there something else I miss?

OK, I checked my archive, that md5sum of QuakeEX.kpf is from September 2021, i.e. it _is old_, i.e. it is older than the rerelease version you are using: horde mode came with update-3, so you need a matching, newer version of QuakeEX.kpf
