### ISSUE TITLE
Packet Overflows

### ISSUE THREAD

**Issue by Flecked42** [sezero/quakespasm#59]
Packet Overflows can happen in the end fight on map https://www.slipseer.com/index.php?resources/i-no-longer-fear-the-ranger-guarding-my-heel.222/

Here's a test save, just go crazy gibing everything and you'll get packet overflows.
Type quad in the console to give yourself quad for easy testing.

[end.zip](https://github.com/sezero/quakespasm/files/12209727/end.zip)

This doesn't happen in Ironwail.
It doesn't happen in vkQuake either, but vkQuake uses FTE999 protocol.

**Comment by Flecked42** [comment]
Someone mentioned MAX_DATAGRAM could be the issue https://github.com/sezero/quakespasm/blob/9ccd014763d1b29413cc2e0dfdae0bc466d3fe85/Quake/quakedef.h#L84

Ironwail increased it to 64000

**Comment by sezero** [comment]
> Someone mentioned MAX_DATAGRAM could be the issue
> Ironwail increased it to 64000

@andrei-drexler, @ericwa: can there be any subtle issues by blindly increasing this?

**Comment by Flecked42** [comment]
Did you try increasing MAX_DATAGRAM and see if the packet overflows go away?

I'm not 100% sure that's the issue, but its worth a shot.

**Comment by Flecked42** [comment]
Found this in the FitzQuake readme https://github.com/sezero/quakespasm/blob/e132da234ba8e9a77e1dcb7f518ace39bec6521d/Misc/fitzquake085.txt#L79 could be useful

**Comment by sezero** [comment]
Joequake recently bumped MAX_DATAGRAM to 64000
https://github.com/j0zzz/JoeQuake/commit/4fcec0071f292595f260e78ccaddb52909d5932d

@ericwa, @Shpoike: can there be any subtle issues by blindly increasing this?

**Comment by sezero** [comment]
MAX_DATAGRAM rasid to 64000 in git. Closing as fixed.
