### ISSUE TITLE
Fog blending/banding issues

### ISSUE THREAD

**Issue by Flecked42** [sezero/quakespasm#76]
QuakeSpasm

![spasm0000](https://github.com/sezero/quakespasm/assets/90434262/a708a260-2f77-453e-812c-e24c308cd251)

Ironwail

![w1m7_2023-08-21_13-58-27](https://github.com/sezero/quakespasm/assets/90434262/3702bd1e-4279-4c6e-845c-0d6c82134039)

I cranked gamma/contrast to max to see it better.

Map is w1m7 from SMEJ https://www.quaddicted.com/filebase/smej_1.13.zip

**Comment by sezero** [comment]
If it's restricted to that map only, then it's minor. Unless someone has a well-tested patch for it..

In any case, is the issue present in latest release (0.95.1), or is it a regression in git?

**Comment by sezero** [comment]
CC: @ericwa, @andrei-drexler

**Comment by Flecked42** [comment]
I use the latest release 0.95.1

the banding could happen in many maps with fog

![spasm0000](https://github.com/sezero/quakespasm/assets/90434262/9a1102ec-5f8f-41dc-b3a7-71f2d0daae64)

**Comment by Flecked42** [comment]
Novum mentioned something about using a "10bit color buffer" https://github.com/sezero/quakespasm/issues/47#issuecomment-1418247674

**Comment by sezero** [comment]
If you or others have a well-tested patch, I'd review and apply it. Otherwise, this will stay as is.

**Comment by andrei-drexler** [comment]
The map uses a grey fog with a value of `0.01`, so in an 8-bit framebuffer there are basically at most 4 distinct color values between black and full-intensity fog (inclusively). Cranking up the gamma/contrast only makes things worse. A 10-bit framebuffer would indeed help, but there would still be significant banding with these exaggerated gamma/contrast settings. Besides the 10-bit framebuffer IW also adds a microscopic amount of dithering to all the shaders specifically to avoid banding, but I think that might be a bit overkill for QS.

**Comment by Flecked42** [comment]
Thanks for the info. Yea the gamma/contrast was way exaggerated just to show it better,

**Comment by sezero** [comment]
OK then. Closing as WONTFIX.
