### ISSUE TITLE
Issue with depth clamp extension

### ISSUE THREAD

**Issue by Flecked42** [sezero/quakespasm#78]
Using current git build.

Issue happens when using the grappling hook from Re:Mobilize https://www.slipseer.com/index.php?resources/re-mobilize.239/

You can test this in the start map.

This example is grappling straight up.

With depth clamp

![spasm0001](https://github.com/sezero/quakespasm/assets/90434262/0411bc7c-2fef-4c15-9709-fa2b11248eae)

Without depth clamp

![spasm0000](https://github.com/sezero/quakespasm/assets/90434262/80bafbb6-4fe4-40b4-bcb5-dc11c22d044d)

**Comment by sezero** [comment]
Sigh...

I'm afraid that patch will go down the drain too.

(CC: @andrey-budko)

**Comment by sezero** [comment]
CC: @j0zzz -- joequake possibly has the same issue.

**Comment by Flecked42** [comment]
Yes right, it does.

**Comment by sezero** [comment]
I went ahead and reverted the patch as of https://github.com/sezero/quakespasm/commit/7c993461f2bec487b2fe1bdcb4f88abdf987197d

Closing as fixed.
