### ISSUE TITLE
[Feature] Search for localization file in engine folder

### ISSUE THREAD

**Issue by 4LT** [sezero/quakespasm#8]
Version: 0.94.1
Platform: Arch Linux 5.13.12

I was trying to figure out why localization was working when I first launched the game, but failed on subsequent attempts.  Turns out I happened to be in my `steamapps/common/Quake/rerelease` directory in order to pull the `mg1` directory into `~/.quakespasm`.

As it happens, the file `QuakeEX.kpf` needs to be in the current working directory in order for localization to function properly.  I think it would be more convenient if the file were searched for from the engine folder, so that users could launch the game from any directory.

**Comment by sezero** [comment]
It was designed that the kpf file would be found under basedir, i.e.
- either quakespasm was copied to rerelease directory
- or quakespasm is run with the `-basedir` command-line switch, e.g.
  `quakespasm -basedir <wherever>/rerelease`

If, instead, you are copying rerelease content into your own quakespasm
directory, you should copy the kpf file too.

Am I missing something?

**Comment by sezero** [comment]
OR: do you actually mean that we should also look at userdir, e.g. like:
```diff
index 2e7dad5..b7e4a1c 100644
--- a/Quake/common.c
+++ b/Quake/common.c
@@ -2547,6 +2547,12 @@ void LOC_LoadFile (const char *file)
 	memset(&archive, 0, sizeof(archive));
 	q_snprintf(path, sizeof(path), "%s/%s", com_basedir, file);
 	rw = SDL_RWFromFile(path, "rb");
+	#if defined(DO_USERDIRS)
+	if (!rw) {
+		q_snprintf(path, sizeof(path), "%s/%s", host_parms->userdir, file);
+		rw = SDL_RWFromFile(path, "rb");
+	}
+	#endif
 	if (!rw)
 	{
 		q_snprintf(path, sizeof(path), "%s/QuakeEX.kpf", com_basedir);
```

(Sorry, cannot fully understand the precise request.)

**Comment by 4LT** [comment]
> OR: do you actually mean that we should also look at userdir,

Yes, this!  Sorry for the confusion.

**Comment by sezero** [comment]
OK, the patch is in.
