### ISSUE TITLE
Border on screenshot

### ISSUE THREAD

**Issue by razzeee** [sezero/quakespasm#89]
https://github.com/sezero/quakespasm/blob/master/Linux/net.sourceforge.quakespasm.Quakespasm.appdata.xml#L49C28-L49C101 has a blue border on top and below

https://github.com/sezero/quakespasm/blob/master/Linux/net.sourceforge.quakespasm.Quakespasm.appdata.xml#L33 has a weird border to the left

**Comment by sezero** [comment]
Old screenshots at sourceforge. May or may not replace some day, but not today..
