### ISSUE TITLE
Good afternoon I have a problem with limits

### ISSUE THREAD

**Issue by Sagara777Sousuke** [sezero/quakespasm#9]
Is it possible to bring them to the limit of very large values or cancel them altogether?
The project is so huge that you need to increase the limits on Brushes to 200 thousand brushes on one card.
increasing the allocated memory in order to use the maximum that can be shoved into the card at such limits.

**Comment by QUINTIX** [comment]
> 1. Host_Error: Mod_Leafs: 130539 Exceds Limit of 100000.

```c
if (count > 32767)
  Host_Error ("Mod_LoadLeafs: %i leafs exceeds limit of 32767.\n", count);
```
is what's in gl_model.c if you want to muck around with it

say add
```c
#DEFINE MAX_LEAVES 0x200000
```
after the `#include`
then change those lines to
```c
if (count > MAX_LEAVES) {
  Host_Error ("Mod_LoadLeafs: %i leafs exceeds limit of %i.\n", count, MAX_LEAVES);
}
```

but I'd advise going back to the drawing board in your level editor of choice to see if you can reduce the number of binary space partition branches before resorting to something as extreme as multiplying the maximum number of visibility leaves 64 fold.

**Comment by Sagara777Sousuke** [comment]
> > 1. Ошибка хоста: Mod_Leafs: 130539 Превышает лимит в 100000.
> 
> ```c
> если (количество > >32767)
>  Ошибка хоста ("Mod_LoadLeafs: %i листьев превышает предел 32767.\n", количество);
> ```
> 
> это то, что есть в [gl_model.c:1542,](sezero/quakespasm/blob/master/Quake/gl_model.c#L1542) ~если вы хотите повозиться с этим~
> 
> ~скажи добавить~
> 
> ```c
> #ОПРЕДЕЛИТЬ МАКСИМАЛЬНЫЕ ЗНАЧЕНИЯ 0x200000
> ```
> 
> ~`#include`~ ~после этого измените эти строки на~
> 
> ```c
> если (количество > MAX_LEAVES) {
>  Host_Error ("Mod_LoadLeafs: %i листьев превышает предел %i.\n", количество, MAX_LEAVES);
> }
> ```
> 
> но я бы посоветовал вернуться к чертежной доске в выбранном вами редакторе уровней, чтобы посмотреть, сможете ли вы уменьшить количество ветвей раздела двоичного пространства, прежде чем прибегать к чему-то столь экстремальному, как умножение максимального количества видимых листьев в 64 раза.
> 
> Правка: до меня доходит, что листовые индексы могут быть 16-битными целыми числами. В этом случае это может не сработать. Другие исходные порты могут поддерживать 32-разрядные конечные индексы. Мне нужно будет провести расследование.
> 
> Дальнейшее редактирование: [bsp2](https://quakewiki.org/wiki/BSP2), который поддерживается, не имеет такого ограничения на видимость листьев. Возможно, вместо этого захочется экспортировать в это. Тем не менее, я бы посоветовал пройти и выполнить оптимизацию, добавив поверхности подсказок по мере необходимости.

Thank you very much for the answer.
I tried to optimize, but I have such a large project that it won't help without increasing the limits.

I already have been using it when compiling BSP2

is there a console command that can increase the leaf limit on the map?

**Comment by QUINTIX** [comment]
> is there a console command that can increase the leaf limit on the map?

Does not look like it. Furthermore, I'm actually having trouble finding a leaf limit of 100000 anywhere. Only one explicitly given I can find is 32767, which _should_ only apply to BSP1.

**Comment by Sagara777Sousuke** [comment]
> > есть ли консольная команда, которая может увеличить лимит листа на карте?
> 
> Не похоже на это. Кроме того, у меня на самом деле возникли проблемы с поиском лимита в 100000 в любом месте. Только один явно заданный, который я могу найти, - 32767, который _должен_ применяться только к BSP1.

Thank you very much for your help.

I climbed optimized but now I run out of memory or something like that.
is there a console command to increase the limit of this parameter?

Hunk_Alloc: Failed 68166160 bytes

Register through the label
Bug fixes
Allocating memory for resources.
-heapsize 1347903

**Comment by QUINTIX** [comment]
There is no console command that I know of to adjust the heap size while the game is running. Fortunately, there is a command line option to have more memory available right on startup. Namely `-heapsize [kilobytes]`

Try
```
-heapsize 262144 
```

from a terminal, in addition to the command line options to specify your map. That'll give you 256 megabytes.

**Comment by Sagara777Sousuke** [comment]
> Насколько мне известно, нет консольной команды для настройки размера кучи во время работы игры. К счастью, есть опция командной строки, чтобы сразу при запуске было доступно больше памяти. Именно `-heapsize [kilobytes]`
> 
> Попробуй
> 
> ```
> -heapsize 262144 
> ```
> 
> с терминала, в дополнение к параметрам командной строки, чтобы указать свою карту. Это даст вам 256 мегабайт.

did not help inserted the command into the shortcut of the game.
Where is the command line in the quake?

**Comment by Sagara777Sousuke** [comment]
Successful compilation logs.
before optimization and after optimization.
if more goes beyond the limits of the allocated memory that I could not apply through the shortcut of the game.

[floor_2021_11_07_v114.log](https://github.com/sezero/quakespasm/files/7612838/floor_2021_11_07_v114.log)
[floor_2021_11_07_v106.log](https://github.com/sezero/quakespasm/files/7612839/floor_2021_11_07_v106.log)

**Comment by Sagara777Sousuke** [comment]
> Насколько мне известно, нет консольной команды для настройки размера кучи во время работы игры. К счастью, есть опция командной строки, чтобы сразу при запуске было доступно больше памяти. Именно `-heapsize [kilobytes]`
> 
> Попробуй
> 
> ```
> -heapsize 262144 
> ```
> 
> с терминала, в дополнение к параметрам командной строки, чтобы указать свою карту. Это даст вам 256 мегабайт.

I will add that I am using Arcane Dimensions mod.
on top of the Quakespasm engine.
Due to the fact that in the usual Quakespasm the map is limited to about 50 floors and then the map is cut off.
and in Arcane Dimensions there is no such limitation.
